-- MySQL Script generated by MySQL Workbench
-- Ne 26. november 2017, 20:39:31 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema forsesk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forsesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forsesk` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema strediska
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema strediska
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `strediska` ;
USE `forsesk` ;

-- -----------------------------------------------------
-- Table `forsesk`.`stredisko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forsesk`.`stredisko` (
  `id_stredisko` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `meno` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT 'názov s diakrit.',
  `status` DATETIME NULL DEFAULT NULL COMMENT 'datetime - last online',
  PRIMARY KEY (`id_stredisko`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `forsesk`.`zaznamy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forsesk`.`zaznamy` (
  `id_stredisko` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `id` VARCHAR(15) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `vaha` INT(11) NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id_stredisko` ASC),
  CONSTRAINT `nachadza_sa`
    FOREIGN KEY (`id_stredisko`)
    REFERENCES `forsesk`.`stredisko` (`id_stredisko`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `forsesk`.`SAP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forsesk`.`SAP` (
  `id_stredisko` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL COMMENT 'FK',
  `sql_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PV` VARCHAR(63) CHARACTER SET 'utf8' NOT NULL,
  `partner` VARCHAR(63) CHARACTER SET 'utf8' NOT NULL,
  `partner_id` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `norma` VARCHAR(7) CHARACTER SET 'utf8' NOT NULL,
  `material_nazov` VARCHAR(63) CHARACTER SET 'utf8' NOT NULL,
  `material_cislo` INT(7) NOT NULL,
  `spz` VARCHAR(9) CHARACTER SET 'utf8' NOT NULL,
  `vodic` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `vazil` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `poznamka` VARCHAR(126) CHARACTER SET 'utf8' NOT NULL,
  `id_paired_brutto` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'FK',
  `id_paired_tara` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'FK',
  `brutto_time` DATETIME NOT NULL,
  `brutto_weight` VARCHAR(7) CHARACTER SET 'utf8' NOT NULL,
  `tara_time` DATETIME NOT NULL,
  `tara_weight` VARCHAR(7) CHARACTER SET 'utf8' NOT NULL,
  `netto_time` DATETIME NOT NULL,
  `netto_weight` VARCHAR(7) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`sql_id`),
  INDEX `zahrnuje_idx` (`id_stredisko` ASC),
  CONSTRAINT `zahrnuje`
    FOREIGN KEY (`id_stredisko`)
    REFERENCES `forsesk`.`stredisko` (`id_stredisko`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `obsahuje_b`
    FOREIGN KEY (`id_paired_brutto`)
    REFERENCES `forsesk`.`zaznamy` (`id_stredisko`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `obsahuje_t`
    FOREIGN KEY (`id_paired_tara`)
    REFERENCES `forsesk`.`zaznamy` (`id_stredisko`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 96
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `forsesk`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forsesk`.`admins` (
  `uniq_id` INT(3) NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `pw` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL COMMENT 'sha1',
  PRIMARY KEY (`uniq_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovak_ci;

USE `strediska` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
